In [93]:
import numpy as np
import pandas as pd


cities = pd.read_csv('data\\cities.csv')
constellations = pd.read_csv('data\\constellations.csv')
meteorshowers = pd.read_csv('data\\meteorshowers.csv')
moon = pd.read_csv('data\\moon_phases_2026.csv')
month = {'january':int(1), 'february':int(2), 'march':int(3), 'april':int(4), 'may':int(5), 'june':int(6), 'july':int(7),'august':int(8),'september':int(9),'october':int(10),'november':int(11),'december':int(12)}


meteorshowers['bestmonth'] = meteorshowers['bestmonth'].map(month)
meteorshowers['endmonth'] = meteorshowers['endmonth'].map(month)
meteorshowers['startmonth'] = meteorshowers['startmonth'].map(month)
constellations['bestmonth'] = constellations['bestmonth'].map(month)


# pd.to_datetime((meteorshowers['startmonth'])*100+(meteorshowers['startday'])+(2026*10000), format = '%Y%m%d')
meteorshowers['startdate'] = pd.to_datetime((meteorshowers['startmonth'])*100+(meteorshowers['startday'])+(2026*10000), format = '%Y%m%d')

# pd.to_datetime((2026*10000)+(meteorshowers['endmonth']*100)+meteorshowers['endday'], format = '%Y%m%d')
meteorshowers['enddate'] = pd.to_datetime((2026*10000)+(meteorshowers['endmonth']*100)+meteorshowers['endday'], format = '%Y%m%d')

# moon['moonphase'].unique()

phase = {'New Moon':0, 'First Quarter' : 0.5, 'Third Quarter':0.5, 'Full Moon': 1 }
moon['percentage'] = moon['moonphase'].map(phase)

constellations = constellations.drop(columns=['besttime'])
constellations

meteorshowers = meteorshowers.drop(columns=['startmonth','startday','endmonth','endday','preferredhemisphere'])

moon = moon.drop(columns=['moonphase','specialevent'])

moon

           date  percentage
0    2026-01-01         NaN
1    2026-01-02         NaN
2    2026-01-03         1.0
3    2026-01-04         NaN
4    2026-01-05         NaN
..          ...         ...
360  2026-12-27         NaN
361  2026-12-28         NaN
362  2026-12-29         NaN
363  2026-12-30         NaN
364  2026-12-31         0.5

[365 rows x 2 columns]

In [283]:
moon['date'] = pd.to_datetime(moon['date'])

In [98]:
moon['percentage'] = moon['percentage'].ffill().fillna(0.5)

moon

           date  percentage
0    2026-01-01         0.5
1    2026-01-02         0.5
2    2026-01-03         1.0
3    2026-01-04         1.0
4    2026-01-05         1.0
..          ...         ...
360  2026-12-27         1.0
361  2026-12-28         1.0
362  2026-12-29         1.0
363  2026-12-30         1.0
364  2026-12-31         0.5

[365 rows x 2 columns]

In [306]:
def star(city):
    meteor_shower_string = ''
    if city not in cities['city'].values:
        meteor_shower_string = f'아쉽지만 {city}에는 별자리 서비스가 제공되지 않습니다!.'
        return meteor_shower_string
    
    
    latitude = cities[cities['city'] == city]['latitude'][0]
    constellations_list = constellations[(constellations['latitudestart'] >= latitude) & (constellations['latitudeend'] <= latitude)]['constellation'].to_list()
    for i in constellations_list:
        meteorshower = meteorshowers.loc[meteorshowers['radiant'] == i,'name'].iloc[0]
        starttime = meteorshowers.loc[meteorshowers['radiant'] == i,'startdate'].iloc[0]
        endtime = meteorshowers.loc[meteorshowers['radiant'] == i,'enddate'].iloc[0]
        moon_list = moon[(moon['date'] >= starttime) & (moon['date'] <= endtime)]
        best_moon_date = moon_list.loc[moon_list['percentage'].idxmin(),'date']
        best_moon_date_str = best_moon_date.to_pydatetime().strftime('%Y년 %m월 %d일')
        meteor_shower_string += f'{city} 에서 {best_moon_date_str}에 {meteorshower} 를 보실수 있습니다.\n'
    return meteor_shower_string

print(star('Abu Dhabi'))

Abu Dhabi 에서 2026년 04월 21일에 Lyrids 를 보실수 있습니다.
Abu Dhabi 에서 2026년 04월 19일에 Eta Aquarids 를 보실수 있습니다.
Abu Dhabi 에서 2026년 10월 10일에 Orionids 를 보실수 있습니다.
Abu Dhabi 에서 2026년 07월 14일에 Perseids 를 보실수 있습니다.

In [299]:
latitude = cities[cities['city'] == 'Abu Dhabi']['latitude'][0]
constellations_list = constellations[(constellations['latitudestart'] >= latitude) & (constellations['latitudeend'] <= latitude)]['constellation'].to_list()
for i in constellations_list:
        meteorshower = meteorshowers.loc[meteorshowers['radiant'] == i,'name'].iloc[0]
        starttime = meteorshowers.loc[meteorshowers['radiant'] == i,'startdate'].iloc[0]
        endtime = meteorshowers.loc[meteorshowers['radiant'] == i,'enddate'].iloc[0]
        moon_list = moon[(moon['date'] >= starttime) & (moon['date'] <= endtime)]
        best_moon_date = moon_list.loc[moon_list['percentage'].idxmin(),'date']
        best_moon_date_str = best_moon_date.to_pydatetime().strftime('%Y년 %m월 %d일')
        # print(meteorshower)
        # print(starttime)
        # print(endtime)
        # print(moon_list)
        print(best_moon_date_str)

2026년 04월 21일
2026년 04월 19일
2026년 10월 10일
2026년 07월 14일

In [286]:
moon_list

          date  percentage
110 2026-04-21         0.0
111 2026-04-22         0.0

In [282]:
moon.info()

<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        365 non-null    str
 1   percentage  365 non-null    float64
dtypes: float64(1), str(1)
memory usage: 5.8 KB

In [274]:
# moon_list = moon[(moon['date'] >= starttime) & (moon['date'] <= endtime)]
moon

           date  percentage
0    2026-01-01         0.5
1    2026-01-02         0.5
2    2026-01-03         1.0
3    2026-01-04         1.0
4    2026-01-05         1.0
..          ...         ...
360  2026-12-27         1.0
361  2026-12-28         1.0
362  2026-12-29         1.0
363  2026-12-30         1.0
364  2026-12-31         0.5

[365 rows x 2 columns]

In [ ]:
# 도시의 위도를 확인 cities
# 위도를 사용해서 해당 도시에 표시되는 별자리 확인 constell
# 별자리를 사용해서 해당 도시에서 볼수 있는 유성우 확인 meteor
# 유성우를 사용해서 해당 유성우를 볼 수 있는 날짜 확인
# 날짜를 사용해서 달의 위상값이 가장 작은 최적 날짜 확인 moon

# 마지막으로 사용자에게 기분좋은 문구 반환